// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ReleaseNotes.FAKE")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","05/02/2021")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ReleaseNotes.FAKE"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "05/02/2021"
